from functions.run_python_file import run_python_file
print("-----Start-----")
print(run_python_file("calculator", "main.py"))
print("-----END-----\n")
print(run_python_file("calculator", "main.py", ["3 + 5"]))
print("-----END-----\n")
print(run_python_file("calculator", "tests.py"))
print("-----END-----\n")
print(run_python_file("calculator", "../main.py"))
print("-----END-----\n")
print(run_python_file("calculator", "nonexistent.py"))
print("-----END-----\n")
print(run_python_file("calculator", "lorem.txt"))
print("-----END-----\n")